### ISSUE TITLE
caseラベル多分間違えてる

### ISSUE THREAD

**Issue by wand2016** [sakamata/livelynk#1]
https://github.com/sakamata/livelynk/blob/c3c153dd07d9deb1469b5c93e613a913a6371ffc/app/Http/Controllers/GoogleHomeController.php#L96

**Comment by sakamata** [comment]
ありがとうございます！初Issue頂きましたので修正しました。
そもそもこのメソッドの呼び出し元も newしてるのに気づいたので後で修正しておきます。
