### ISSUE TITLE
ソート順のバリデーション

### ISSUE THREAD

**Issue by wand2016** [sakamata/livelynk#2]
https://github.com/sakamata/livelynk/blob/3ae941c91b56deaedf0ef1a26af0c192fcb61ed2/app/Http/Controllers/AdminUserController.php#L45

正規表現`/asc|desc/`は`cascade`や`description`にもマッチしてしまう

`/^(asc|desc)$/`とするか、もしくは`Illuminate\Validation\Rule`をuseして

```php
'id' => ['nullable', Rule::in(['asc', 'desc'])],
```

としたほうがよい

**Comment by sakamata** [comment]
ありがとうございます。今見ると確かにこれはヤバイですね。以下のController含め正規表現を修正しました。
Rule::in() 使いこなせると良さげですね。
しかしまた別のバグを見つけてしまった。
app\Http\Controllers\AdminMacAddressController.php
app\Http\Controllers\AdminUserController.php

**Comment by sakamata** [comment]
close
